### ISSUE TITLE
Setprice on enchanted item error

### ISSUE THREAD

**Issue by MesterDavid** [mastercake10/uShop#7]
15:50:21 INFO]: Dani101Dani issued server command: /ushop setprice 5500
[15:50:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ushop' in plugin uShop v2.1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[S.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[S.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [S.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [S.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [S.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey()Lorg/bukkit/NamespacedKey;
        at xyz.spaceio.ushop.CustomItem.lambda$2(CustomItem.java:95) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[?:1.8.0_221]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.allMatch(Unknown Source) ~[?:1.8.0_221]
        at xyz.spaceio.ushop.CustomItem.matches(CustomItem.java:94) ~[?:?]
        at xyz.spaceio.ushop.Main.lambda$4(Main.java:203) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_221]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_221]
        at xyz.spaceio.ushop.Main.findCustomItem(Main.java:203) ~[?:?]
        at xyz.spaceio.ushop.uShopCmd.onCommand(uShopCmd.java:46) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[S.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more
>

**Comment by mastercake10** [comment]
Spigot 1.12 is not supported by uShop v2.
